-- 코드를 입력하세요
-- INGREDITENT_TYPE 성분 타입
-- 성분 타임과 성분 타입에 대한 아이스크림 총 주문량을 작은 순서대로 
-- 총 주문량을 나타내는 컬럼명은 TOTAL_ORDER
SELECT B.INGREDIENT_TYPE, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF A JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE 
ORDER BY TOTAL_ORDER ASC;