-- 코드를 입력하세요
-- 2022년 1월의 카테고리 별 도서 판매량 합산 
-- 카테고리, 총 판매량 리스트를 출력
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE LIKE '2022-01%'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC;
